# Generated by Django 6.0.4 on 2026-05-02 15:37

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GaleriÖğesi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("başlık", models.CharField(max_length=200)),
                ("açıklama", models.TextField(blank=True)),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("maçlar", "Maçlar"),
                            ("antrenman", "Antrenman"),
                            ("etkinlik", "Etkinlikler"),
                        ],
                        default="maçlar",
                        max_length=50,
                    ),
                ),
                (
                    "turu",
                    models.CharField(
                        choices=[("resim", "Resim"), ("video", "Video")],
                        default="resim",
                        max_length=10,
                    ),
                ),
                (
                    "resim",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "video_dosya",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                ("oluşturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("sıra", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-sıra", "-oluşturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="Haber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("başlık", models.CharField(max_length=200)),
                ("içerik", models.TextField()),
                (
                    "görsel",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("yayınlama_tarihi", models.DateTimeField(auto_now_add=True)),
                ("güncellenme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-yayınlama_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="KurucuUye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_soyad", models.CharField(max_length=120)),
                (
                    "unvan",
                    models.CharField(help_text="Başkan, Sekreter…", max_length=80),
                ),
                ("gorev", models.CharField(blank=True, max_length=120)),
                ("telefon", models.CharField(max_length=20)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="yonetim/"),
                ),
                ("sira", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Kurucu Üye",
                "verbose_name_plural": "Kurucu Üyeler",
                "ordering": ["sira"],
            },
        ),
        migrations.CreateModel(
            name="Takim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=200)),
                (
                    "logo",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Oyuncu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100)),
                ("pozisyon", models.CharField(max_length=50)),
                ("numara", models.IntegerField()),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "takim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oyuncular",
                        to="website.takim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ev_sahibi", models.CharField(max_length=100)),
                ("misafir", models.CharField(max_length=100)),
                ("ev_sahibi_gol", models.IntegerField(default=0)),
                ("misafir_gol", models.IntegerField(default=0)),
                ("tarih", models.DateTimeField()),
                ("lig", models.CharField(max_length=100)),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("kazanildi", "Kazanıldı"),
                            ("berabere", "Berabere"),
                            ("kaybedildi", "Kaybedildi"),
                            ("gelecek", "Gelecek"),
                        ],
                        default="gelecek",
                        max_length=20,
                    ),
                ),
                (
                    "takim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maclar",
                        to="website.takim",
                    ),
                ),
            ],
        ),
    ]
