# Generated by Django 5.0.14 on 2026-05-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galeriöğesi",
            name="turu",
        ),
        migrations.AlterField(
            model_name="galeriöğesi",
            name="başlık",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="galeriöğesi",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="YouTube veya başka bir video linki", null=True
            ),
        ),
    ]
